name: Android Studio Keeper
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  maintain:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        
    - name: Install dependencies
      run: |
        npm install playwright
        npx playwright install chromium
        
    - name: Run session keeper
      env:
        AS_USER: ${{ secrets.AS_USER }}
        AS_PASS: ${{ secrets.AS_PASS }}
      run: node keeper.js
      
    - name: Persist session data
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"
        git add session.json status.json logs/
        git commit -m "Update session: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes"
        git push
